runtime: nodejs14

env_variables:
  apiKey: $ENV_API_KEY
  authDomain: $ENV_AUTH_DOMAIN
  projectId: $ENV_PROJECT_ID
  storageBucket: $ENV_STORAGE_BUCKET
  messagingSenderId: $ENV_MESSAGING_SENDER_ID
  appId: $ENV_APP_ID
  measurementId: $ENV_MEASUREMENT_ID

handlers:
  - url: /sitemap.xml
    static_files: sitemap.xml
    upload: sitemap.xml
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
