runtime: nodejs14

env_variables:
  apiKey: 'AIzaSyCRzXjOMtEC-OI6DLOPL9MxD5pOpbANTWs'
  authDomain: 'anirbmuk.firebaseapp.com'
  projectId: 'anirbmuk'
  storageBucket: 'anirbmuk.appspot.com'
  messagingSenderId: '468979340135'
  appId: '1:468979340135:web:6a551129b6806274edd5c2'
  measurementId: 'G-R1DT03T0TL'

handlers:
  - url: /sitemap.xml
    static_files: sitemap.xml
    upload: sitemap.xml
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
