name: anirbmuk repo branch-merges

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node-modules-pre
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-anirbmuk-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install node_modules
        if: steps.cache-node-modules-pre.outputs.cache-hit != 'true'
        run: yarn install

  check:
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-anirbmuk-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Check linting
        run: yarn lint

      - name: Check prettier
        run: yarn format:check

  build:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-anirbmuk-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build anirbmuk project
        run: yarn build:ssr:prod

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-anirbmuk
          path: dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          name: dist-anirbmuk
          path: dist
      - uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          ENV_API_KEY: ${{ secrets.ENV_API_KEY }}
          ENV_AUTH_DOMAIN: ${{ secrets.ENV_AUTH_DOMAIN }}
          ENV_PROJECT_ID: ${{ secrets.ENV_PROJECT_ID }}
          ENV_STORAGE_BUCKET: ${{ secrets.ENV_STORAGE_BUCKET }}
          ENV_MESSAGING_SENDER_ID: ${{ secrets.ENV_MESSAGING_SENDER_ID }}
          ENV_APP_ID: ${{ secrets.ENV_APP_ID }}
          ENV_MEASUREMENT_ID: ${{ secrets.ENV_MEASUREMENT_ID }}
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy anirbmuk cloud
        run: |
          cd ${{ github.workspace }}
          yarn deploy:gae
